# -*- mode: ruby -*-
# vi: set ft=ruby :


Vagrant.configure("2") do |config|
	# use 16.04 because 14.04's go version is ooooooooooooooooooooold
	config.vm.box = "ubuntu/xenial64"

	# Disable automatic box update checking. If you disable this, then
	# boxes will only be checked for updates when the user runs
	# `vagrant box outdated`. This is not recommended.
	# config.vm.box_check_update = false


	config.vm.network "forwarded_port", guest: 80, host: 8080
	config.vm.network :private_network, ip: "172.27.0.3"
	config.vm.synced_folder "../", "/vagrant"
	config.vm.provider "virtualbox" do |vb|
	  vb.gui = false
		vb.cpus = "4"
	  vb.memory = "4096"
	end
  config.vm.provision :shell, path: "bootstrap.sh"
end
