services:
  gochan:
    build:
      context: ..
      dockerfile: docker/Dockerfile
      args:
        - GOCHAN_PORT=80
        - GOCHAN_SITE_HOST=127.0.0.1
        - GOCHAN_DB_TYPE=mariadb
        - GOCHAN_DB_HOST=gochan-mariadb:3306
    container_name: gochan-server
    ports:
      - "80:80"
    volumes:
      - ./volumes/gochan/log:/var/log/gochan
      - ./volumes/gochan/www:/var/www/gochan
      - ./volumes/gochan/config:/etc/gochan
    networks:
      - gochan-bridge
    depends_on:
      - mariadb

  mariadb:
    image: mariadb:11.5.2-noble
    container_name: gochan-mariadb
    tty: true
    expose:
      - "3306"
    networks:
      - gochan-bridge
    environment:
      - MARIADB_ROOT_PASSWORD=root
      - MARIADB_DATABASE=gochan
      - MARIADB_USER=gochan
      - MARIADB_PASSWORD=gochan
    volumes:
      - ./volumes/mariadb:/var/lib/mysql

networks:
  gochan-bridge:
    name: gochan-bridge
    driver: bridge
